//name: Group ETL Workflows for group 32

on:
  schedule:
    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
            
      - name: Install system dependencies for sf package
        run: |
          sudo apt-get install libgdal-dev libgeos-dev libproj-dev
      - name: Install system dependencies for rnaturalearth package
        run: |
          sudo apt-get install libudunits2-dev

      - name: Install tidyr package
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages("tidyr")'
          
      //- name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr", "RSQLite", "sf", "rnaturalearth", "rnaturalearthdata"))'

      - name: Execute database update script
        run: |
          Rscript R/update_database.R
          
      - name: Add files
        run: |
          git config --global user.email "gattaniparag2812@gmail.com"
          git config --global user.name "paraggattani"
          git add --all figures/
      - name: Commit files
        run: |
          git commit -m "Updates"
      //- name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
